# General Jekyll Config
exclude: [".gitignore", "README.md", "Gemfile", "Gemfile.lock", "CNAME"]

teams:
  - name: SEP
    url: http://www.sep.com
    location: Carmel
    contact: Matt Swanson
    contact_email: mdswanson@sep.com

  - name: DeveloperTown
    url: http://www.developertown.com/
    location: Broad Ripple
    contact: Jon Nolen
    contact_email: jon.nolen@developertown.com
    
  - name: Interactive Intelligence
    url: http://www.inin.com/
    location: 465 &amp; 79th
    contact: John Vetter
    contact_email: John.Vetter@inin.com
